name: my_flutter_app
description: A new Flutter project.

environment:
  sdk: '>=3.4.0 <4.0.0'  # Define la versión mínima del SDK de Dart

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  url_launcher: ^6.1.8
  flutter_shaders: ^0.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter  # Incluye el paquete de pruebas de Flutter

flutter:
  uses-material-design: true  # Indica que el proyecto usa diseño material
